#!/usr/bin/expect -f
set ip [lindex $argv 0]

if { $ip == ""} {
	puts " backdoor <ip-address>";
} else {
	spawn ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ruser@$ip
	expect "assword:"
	send "rpassword\r"
	interact
}
